// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagmentApp.DataLayer.EF;

namespace OrderManagmentApp.DataLayer.Migrations
{
    [DbContext(typeof(OrderManagmentAppContext))]
    [Migration("20210409070712_addNullableSumAndAdvance")]
    partial class addNullableSumAndAdvance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Agreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Good")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emeil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Advance")
                        .HasColumnType("money");

                    b.Property<decimal?>("ContractSum")
                        .HasColumnType("money");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfCreating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Good")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<int?>("ShipmentDestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("ShipmentSpecialistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ShipmentDestinationId");

                    b.HasIndex("ShipmentSpecialistId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.OrderAgreement", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("AgreementId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "AgreementId");

                    b.HasIndex("AgreementId")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderAgreements");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.OrderInFactory", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfPayment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentedSum")
                        .HasColumnType("money");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateOfOrder")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateOfPayment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateOfSet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateOfShipment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderByALutehs");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.ShipmentDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Destination")
                        .IsUnique()
                        .HasFilter("[Destination] IS NOT NULL");

                    b.ToTable("ShipmentDestinations");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.ShipmentSpecialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Specialist")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShipmentSpecialists");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Agreement", b =>
                {
                    b.HasOne("OrderManagmentApp.BusinessLogic.Models.Customer", "Customer")
                        .WithMany("Agreements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Customer", b =>
                {
                    b.OwnsOne("OrderManagmentApp.BusinessLogic.Models.Company", "Company", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BankAccount")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TaxPayerId")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Order", b =>
                {
                    b.HasOne("OrderManagmentApp.BusinessLogic.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("OrderManagmentApp.BusinessLogic.Models.Manager", "Manager")
                        .WithMany("OrderEntities")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("OrderManagmentApp.BusinessLogic.Models.ShipmentDestination", "ShipmentDestination")
                        .WithMany("Orders")
                        .HasForeignKey("ShipmentDestinationId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("OrderManagmentApp.BusinessLogic.Models.ShipmentSpecialist", "ShipmentSpecialist")
                        .WithMany("Orders")
                        .HasForeignKey("ShipmentSpecialistId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Customer");

                    b.Navigation("Manager");

                    b.Navigation("ShipmentDestination");

                    b.Navigation("ShipmentSpecialist");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.OrderAgreement", b =>
                {
                    b.HasOne("OrderManagmentApp.BusinessLogic.Models.Agreement", "Agreement")
                        .WithOne("OrderAgreement")
                        .HasForeignKey("OrderManagmentApp.BusinessLogic.Models.OrderAgreement", "AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagmentApp.BusinessLogic.Models.Order", "Order")
                        .WithOne("OrderAgreement")
                        .HasForeignKey("OrderManagmentApp.BusinessLogic.Models.OrderAgreement", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agreement");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.OrderInFactory", b =>
                {
                    b.HasOne("OrderManagmentApp.BusinessLogic.Models.Order", "Order")
                        .WithOne("OrderInFactory")
                        .HasForeignKey("OrderManagmentApp.BusinessLogic.Models.OrderInFactory", "OrderId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Agreement", b =>
                {
                    b.Navigation("OrderAgreement");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Customer", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Manager", b =>
                {
                    b.Navigation("OrderEntities");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.Order", b =>
                {
                    b.Navigation("OrderAgreement");

                    b.Navigation("OrderInFactory");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.ShipmentDestination", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagmentApp.BusinessLogic.Models.ShipmentSpecialist", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
